name: "dynamic Pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options: [apply, destroy]
      environment:
        description: "Environment"
        required: true
        type: choice
        options: [dev, sit, production]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  # 1. डायनामिक डिस्कवरी जॉब
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          # यह आपके modules/ फोल्डर के अंदर से सभी रिसोर्स पिक करेगा
          # और workspace का नाम: {folder_name}-{environment} बना देगा
          ENV="${{ inputs.environment }}"
          JSON_OUTPUT=$(ls -d modules/* | jq -R . | jq -s -c --arg env "$ENV" 'map({dir: ., ws: (. | split("/") | last + "-" + $env)})')
          echo "matrix=$JSON_OUTPUT" >> $GITHUB_OUTPUT

  
