name: "dynamic Pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options: [apply, destroy]
      environment:
        description: "Environment"
        required: true
        type: choice
        options: [dev, sit, production]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:

  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_resources: ${{ steps.set-matrix.outputs.has_resources }}
    steps:
      - name: Checkout Org1 Repo
        uses: actions/checkout@v4
        with:
          repository: aayuORG1/project1 
          token: ${{ secrets.PAT_TOKEN }} 

      - id: set-matrix
        run: |
          if [ -d "modules" ] && [ "$(ls -A modules/)" ]; then
            ENV="${{ inputs.environment }}"
            JSON_OUTPUT=$(ls -d modules/* | grep "/" | jq -R . | jq -s -c --arg env "$ENV" 'map({dir: ., ws: (. | split("/") | last + "-" + $env)})')
            echo "matrix=$JSON_OUTPUT" >> $GITHUB_OUTPUT
            echo "has_resources=true" >> $GITHUB_OUTPUT
          else
            echo "has_resources=false" >> $GITHUB_OUTPUT
          fi


  tflint:
    needs: discover-resources
    strategy:
      matrix:
        resource: ${{ fromJSON(needs.discover-resources.outputs.matrix) }}    
    uses: aayuORG1/project1/.github/workflows/docker-tflint.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ matrix.resource.dir }}
    secrets: inherit
