name: "dynamic Pipeline"

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options: [apply, destroy]
      environment:
        description: "Environment"
        required: true
        type: choice
        options: [dev, sit, production]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  # 1. डायनामिक डिस्कवरी जॉब
  discover-resources:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          ENV="${{ inputs.environment }}"
          # यह कमांड सुनिश्चित करती है कि केवल फोल्डर ही पिक हों
          JSON_OUTPUT=$(ls -d modules/* | grep "/" | jq -R . | jq -s -c --arg env "$ENV" 'map({dir: ., ws: (. | split("/") | last + "-" + $env)})')
          echo "matrix=$JSON_OUTPUT" >> $GITHUB_OUTPUT


  tflint:
    needs: discover-resources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: ${{ fromJSON(needs.discover-resources.outputs.matrix) }}
    steps:
      - name: Call TFLint Workflow
        uses: aayuORG1/project1/.github/workflows/docker-tflint.yml@main
        with:
          environment: ${{ inputs.environment }}
          working_directory: ${{ matrix.resource.dir }}
        secrets:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
