name: "Master Pipeline"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      working_directory:
        description: "Terraform Folder"
        required: false
        default: "."
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  tflint:
    uses: aayuORG1/project1/.github/workflows/docker-tflint.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
    secrets:     
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      personal_access_token: ${{ secrets.ACTION_TOKEN}}
