name: "Master Pipeline"

on:
  workflow_dispatch:
    inputs:    
      action:
        description: "Choose action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - sit
          - production
      working_directory:
        description: "Terraform Folder"
        required: false
        default: "."
        type: string

permissions:
  id-token: write
  contents: read
  actions: read

jobs:  
  detect-dir:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dir.outputs.dir }}
    steps:
      - uses: actions/checkout@v4
      - id: set-dir
        run: |       
          INPUT_DIR="${{ inputs.working_directory }}"
          if [[ "$INPUT_DIR" == "." ]]; then
            # Yahan apna auto-detection logic lagayein
            DETECTED=$(ls -d child-modules/* | head -n1) 
            echo "dir=$DETECTED" >> "$GITHUB_OUTPUT"
          else
            echo "dir=$INPUT_DIR" >> "$GITHUB_OUTPUT"
          fi
  tflint:
    needs: detect-dir
    uses: aayuORG1/project1/.github/workflows/docker-tflint.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ needs.detect-dir.outputs.dir }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  tfsec:
    needs: detect-dir
    uses: aayuORG1/project1/.github/workflows/docker-tfsec.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ needs.detect-dir.outputs.dir }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  tftest:
    needs: detect-dir
    uses: aayuORG1/project1/.github/workflows/docker-tftest.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ needs.detect-dir.outputs.dir }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  tfinit_validate_plan:
    uses: aayuORG1/project1/.github/workflows/docker-tf-plan.yml@main
    needs: [tflint, tfsec, tftest]
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}     
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  opa-policy-evaluation:
    uses: aayuORG1/project1/.github/workflows/docker-opa-policy.yml@main
    needs: [tflint, tfsec, tftest, tfinit_validate_plan]
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      
  manual-validation:
    needs: [opa-policy-evaluation]
    uses: aayuORG1/project1/.github/workflows/docker-tf-approve.yml@main
    with:
      environment: approval
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      

  tf_apply:
    needs: [manual-validation]
    uses: aayuORG1/project1/.github/workflows/docker-tf-apply.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    
  tf_destroy:
    needs: [tf_apply]
    if: github.event.inputs.action == 'destroy'
    uses: aayuORG1/project1/.github/workflows/docker-tf-destroy.yml@main
    with:
      environment: ${{ inputs.environment }}
      working_directory: ${{ inputs.working_directory }}
    secrets:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    
